// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KVeztMOUObCTyWG86brXHtI2NiT1fGQ',
    appId: '1:584697826968:web:adbe8c1e4da47bea9a4aed',
    messagingSenderId: '584697826968',
    projectId: 'passage-dd2a4',
    authDomain: 'passage-dd2a4.firebaseapp.com',
    storageBucket: 'passage-dd2a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-EliE70ot10uFS_OKKP5caP0p5VLlRqo',
    appId: '1:584697826968:android:a85fa3f05a9eb1f19a4aed',
    messagingSenderId: '584697826968',
    projectId: 'passage-dd2a4',
    storageBucket: 'passage-dd2a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgRVb9Bxq20rzJcEf6XuoqTGmCi37rbA',
    appId: '1:584697826968:ios:01b495cd29a706109a4aed',
    messagingSenderId: '584697826968',
    projectId: 'passage-dd2a4',
    storageBucket: 'passage-dd2a4.firebasestorage.app',
    iosBundleId: 'com.getpassage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRgRVb9Bxq20rzJcEf6XuoqTGmCi37rbA',
    appId: '1:584697826968:ios:da4d315c10354ec99a4aed',
    messagingSenderId: '584697826968',
    projectId: 'passage-dd2a4',
    storageBucket: 'passage-dd2a4.firebasestorage.app',
    iosBundleId: 'com.example.passage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KVeztMOUObCTyWG86brXHtI2NiT1fGQ',
    appId: '1:584697826968:web:3bbc2d72e64d03269a4aed',
    messagingSenderId: '584697826968',
    projectId: 'passage-dd2a4',
    authDomain: 'passage-dd2a4.firebaseapp.com',
    storageBucket: 'passage-dd2a4.firebasestorage.app',
  );
}
